config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home' # sets pages home view as root
  resources :articles do
    resources :comments
  end

  get 'about', to: 'pages#about' # redirects to pages/about view

  get 'login', to: 'login#login_form', as: 'login'
  post 'login', to: 'login#login', as: 'login_post'
  get 'logout', to: 'login#logout', as: 'logout'

  get 'register', to: 'register#register_form', as: 'register'
  post 'register', to: 'register#register', as: 'register_post'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# Represents an article
class Article < ApplicationRecord
  has_one_attached :image_file
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 10..85 }
  validates :author, presence: true, length: { minimum: 5 }
  validates :excerpt, presence: true, length: { in: 15..175 }
  validates :text, presence: true

  # If search parameter is passed searches for articles with titles that
  # match the search parameter, otherwise retrieves all articles from the db
  def self.search(search)
    if search
      all.where('lower(title) LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

# Represents a comment of an article
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true, length: { in: 2..255 }
end

app/models/user.rb
# frozen_string_literal: true

# Blog's user
class User < ApplicationRecord
  has_secure_password
  has_many :comments, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main application controller
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_user_username

  # User id is set in a session variable, returns current user object,
  # otherwise returns nil
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def current_user_username
    @current_user ||= User.find(session[:user_id])

    local_part = @current_user.email[/^[^@]+/]

    local_part.split('.').map(&:capitalize).join(' ')
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Manages actions with articles
class ArticlesController < ApplicationController
  before_action :require_admin
  skip_before_action :require_admin, only: %i[index show]

  def index
    @articles = Article.search(params[:search])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    @updated_article = article_params

    @updated_article['image'] = nil unless @updated_article['image_file'].nil?

    if @article.update(@updated_article)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :author, :image_file, :excerpt,
                                    :text)
  end

  def require_admin
    if !current_user.nil?
      unless current_user.is_admin?
        render plain: 'You must be log in as admin to access this section',
               status: 403
      end
    else
      render plain: 'You must be log in as admin to access this section',
             status: 403
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Manages actions with comments
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(comment_params)
    @comment.article = @article
    @comment.user = current_user
    @comment.username = current_user_username

    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to(article_path(@article), flash: { error: @comment.errors })
    end
  end

  def destroy
    article = Article.find(params[:article_id])

    @comment = article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/login_controller.rb
# frozen_string_literal: true

# Handles user login and logout
class LoginController < ApplicationController
  def login_form
    @user = User.new
  end

  # Authenticates a user and saves user id in session
  def login
    @request_user = User.new(user_params)

    user = User.find_by(email: @request_user.email)

    if user&.authenticate(@request_user.password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'Email or password is invalid'
      redirect_to action: :login_form
    end
  end

  # User log out
  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Manages actions with pages
class PagesController < ApplicationController
  def home; end

  def about; end
end

app/controllers/register_controller.rb
# frozen_string_literal: true

# Manages user registration
class RegisterController < ApplicationController
  # before_action :check_input_fields_are_not_empty, only: [:register]
  def register_form
    @user = User.new
  end

  def register
    check_input_fields_are_not_empty(user_params)
    check_passwords_match(user_params)
    check_email_is_unique(user_params[:email])

    save_new_user(user_params)

    redirect_to root_path
  rescue StandardError => e
    flash[:error] = e
    redirect_to action: :register_form
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def check_input_fields_are_not_empty(user_params)
    input_fields_empty = user_params[:email] == '' || user_params[:password] == '' ||
                         user_params[:password_confirmation] == ''
    raise 'Input fields cannot be empty' if input_fields_empty
  end

  def check_passwords_match(user_params)
    raise 'Passwords do not match' if user_params[:password] != user_params[:password_confirmation]
  end

  def check_email_is_unique(email)
    registered_user = User.find_by(email: email)

    raise 'This email is already registered' if registered_user
  end

  def save_new_user(user_params)
    @new_user = User.new(user_params)
    @new_user.is_admin = false
    @new_user.save

    session[:user_id] = @new_user.id
  end
end

app/controllers/sessions_controller.rb
# Handles user login and logout
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  # Authenticates a user and saves user id in session
  def create
    @request_user = User.new(user_params)

    user = User.find_by(email: @request_user.email)

    if user && user.authenticate(@request_user.password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = 'Email or password is invalid'
      redirect_to action: :new
    end
  end

  # User log out
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# ArticlesHelper
module ArticlesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# CommentsHelper
module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

# PagesHelper
module PagesHelper
end

app/helpers/register_helper.rb
# frozen_string_literal: true

# RegisterHelper
module RegisterHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# SessionsHelper
module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# UsersHelper
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="alert-danger py-2 px-3 mb-2">
      <h4>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h4>
      <ul class="my-0">
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image_file, "Image" %><br>
    <%= form.file_field :image_file, accept: "image/*", text: @article.image %>
  </div>

  <div class="form-group">
    <%= form.label :excerpt %>
    <%= form.text_field :excerpt, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control", rows: 5 %>
  </div>

  <%= form.submit class: "btn btn-primary" %>

<% end %>

app/views/articles/edit.html.erb
<div class="container mb-5">
  <h1 class="mb-3 pt-3">Edit article</h1>

  <%= render 'form' %>

  <div class="mt-3">
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-11">
      <div class="row my-3 pb-2 mx-0 border-bottom justify-content-between">
        <h1 class="my-0">Articles</h1>
        <%= form_tag(articles_path, method: :get, class: "form-inline") do %>
          <%= text_field_tag(:search, params[:search], class: "form-control mr-2", placeholder: "Search") %>
          <%= submit_tag("Search", class: "btn btn-outline-success") %>
        <% end %>
      </div>
      <% if current_user && current_user.is_admin %>
        <div class="mb-2">
          <%= link_to 'New article', new_article_path %>
        </div>
      <% end %>
      <% @articles.each do |article| %>
        <div class="article">
          <div class="row">
            <div class="col-sm-4">
            <%= link_to article_path(article) do%>
              <% if article.image_file.attached? %>
                <%= image_tag url_for(article.image_file), class: "article-image-index mb-3"%>
              <% elsif article.image %>
                <%= image_tag article.image, class: "article-image-index mb-3" %>
              <% else %>
              <% end %>
            <% end %>
            </div>
            <div class="col-sm-8">
              <%= link_to article_path(article) do%>
                <h2 class="mb-2"><%= article.title %></h2>
              <% end %>
              <div class="row mx-0">
                <p class="acticle-metadata-index mb-2">By <%= article.author %></p>
                <p class="acticle-metadata-index mb-2 mx-3">
                  Published on <%= article.created_at.strftime("%Y-%m-%d") %>
                </p>
              </div>
              <p>
                <%= article.excerpt %>
              </p>
              <div class="row mx-0">
                <%= link_to "Read more", article_path(article), class: "btn btn-primary", role: "button" %>
                <% if current_user && current_user.email == 'admin@techblog.com'%>
                  <%= link_to "Edit", edit_article_path(article), class: "mx-4" %>
                  <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container mb-5">
  <h1 class="mb-3 pt-3">New article</h1>

  <%= render 'form' %>

  <div class="mt-3">
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="article">
    <h1 class="mt-3"><%= @article.title %></h1>
    <p class="acticle-author-index mb-3">By <%= @article.author %></p>
    <div class="row px-3 my-2">
      <% if current_user && current_user.is_admin %>
        <%= link_to "Edit", edit_article_path(@article) %>
        <%= link_to 'Delete', article_path(@article), class: "mx-3", method: :delete,
          data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <% if @article.image_file.attached? %>
      <%= image_tag url_for(@article.image_file), class: "article-image mb-3"%>
    <% elsif @article.image %>
      <%= image_tag @article.image, class: "article-image mb-3" %>
    <% else %>
    <% end %>
    <%= simple_format(@article.text) %>
    <div class="border-bottom mb-3"></div>
    <% if current_user %>
      <%= render "comments/form" %>
    <% else %>
      <div class="alert alert-warning">You have to be <%= link_to "logged in", login_path, class: "alert-link" %> to comment.</div>
    <% end %>
    <p class="lead font-weight-bold mb-3"><%= pluralize(@article.comments.count, "comment") %></p>
    <%= render @article.comments.select(&:persisted?) %>
    <%= link_to "Back to all articles", articles_path %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="mb-2">
  <div class="row mx-0">
    <p class="font-weight-bold mb-2"><%= comment.username %></p>
    <% if comment.created_at && comment.user %>
      <p class="mx-2 text-secondary"><%= comment.created_at.strftime("%Y-%m-%d") %></p>
      <% if current_user && (current_user.id == comment.user.id || current_user.is_admin) %>
        <%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </div>
  <p><%= comment.body %></p>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ], class: "mb-3" do |form| %>
  <% if flash[:error] %>
    <div id="error_explanation" class="alert-danger py-2 px-3 mb-2">
      <h4>
        <%= pluralize(flash[:error]["body"].count, "error") %> prohibited
        this comment from being saved:
      </h4>
      <ul class="my-0">
        <% flash[:error]["body"].each do |msg| %>
          <li><%= "comment #{msg}" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :body, "Add a comment", class: "lead" %><br>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <%= form.submit "Submit", class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <%= link_to "Tech blog", "/", class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", "/", class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Articles", "/articles", class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "About", "/about", class: "nav-link"%>
          </li>
        </ul>
        <% if current_user %>
          <p class="mx-3 my-auto"><%= current_user_username %></p>
          <%= link_to "Log Out", logout_path, class: "btn btn-outline-primary" %>
        <% else %>
          <%= link_to "Register", register_path, class: "btn btn-outline-primary mr-3" %>
          <%= link_to "Login", login_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/login/login_form.html.erb
<div id="login-form" class="col-md-4">
  <section>
    <h1>Login</h1>
    <hr/>
    <%= form_with model: @user, url: login_post_path do |form| %>
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.submit "Login", class: "btn btn-primary btn-block"%>
      </div>
    <% end %>
  </section>
</div>

app/views/pages/about.html.erb
<div class="container">
  <h1 class="mt-3">About</h1>
  <p>
    Tech blog is a technology blog founded & managed by Joe Doe. Tech blog is a destination
    which updates you about the latest technology by providing info on tech news, gadgets, how
    to's, apps & softwares and much more... Our aim is to look for Tech In Every Thing. Our
    goal is providing you information about everything which relates
    to tech and we hope you would be satisfied by visiting this blog. Your
    suggestions are always welcome.
  </p>
</div>

app/views/pages/home.html.erb
<div id="home-container" class="container-fluid">
  <div id="home-div" class="text-center text-light">
    <h1 class="display-4">Welcome to my technology blog</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
    <hr class="my-4">
    <%= link_to "Browse articles", "articles", class: "btn btn-primary", role: "button"%>
  </div>
</div>

app/views/register/register_form.html.erb
<div id="register-form" class="col-md-4">
  <section>
    <h1>Register</h1>
    <hr/>
    <%= form_with model: @user, url: register_post_path do |form| %>
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation, "Confirm password" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.submit "Register", class: "btn btn-primary btn-block"%>
      </div>
    <% end %>
  </section>
</div>